server {
  listen 80;
  root /usr/share/nginx/html;
  location / { try_files $uri $uri/ /index.html; }
  location /api/ { proxy_pass http://backend:8000/api/; }
  location /uploads/ { proxy_pass http://backend:8000/uploads/; }
  location /demo-images/ { proxy_pass http://backend:8000/demo-images/; }
}
